routers:
  hosts:
    cisco.lan.luckyh.de:
  vars:
    ansible_network_os: cisco.ios.ios
    ansible_user: ansible
    ansible_password: newsys
    ansible_become: yes
    ansible_become_pass: newsys
    ansible_connection: ansible.netcommon.network_cli
ucserver:
  hosts:
    DC01-ucs.lan.luckyh.de:
    DC02-ucs.lan.luckyh.de:
  vars:
    ansible_user: ansible
    ansible_password: newsys
NAS:
  hosts:
    TRUENAS1.lan.luckyh.de:
    TRUENAS2.lan.luckyh.de:
  vars:
    ansible_user: ansible
    ansible_password: newsys

proxmox:
  hosts:
    PVE1.lan.luckyh.de:
    PVE2.lan.luckyh.de:
linux:
  hosts:
    DC01-ucs.lan.luckyh.de:
    DC02-ucs.lan.luckyh.de:
    gardenpi.lan.luckyh.de:
    octopi.lan.luckyh.de:
  vars:
    ansible_user: ansible
    ansible_password: newsys
    ansible_become: yes
    ansible_become_pass: newsys
