routers:
  hosts:
    cisco.lan.luckyh.de:
  vars:
    ansible_network_os: cisco.ios.ios
    ansible_user: admin
    ansible_password: newsys99
    ansible_become: yes
    ansible_become_pass: newsys99
    ansible_connection: ansible.netcommon.network_cli
ucserver:
  hosts:
    DC01-ucs.lan.luckyh.de:
    DC02-ucs.lan.luckyh.de:
  vars:
    ansible_user: root
    ansible_password: kawa$aki
NAS:
  hosts:
    TRUENAS1.lan.luckyh.de:
    TRUENAS2.lan.luckyh.de:
  vars:
    ansible_user: nasadmin
    ansible_password: na5adM!n

proxmox:
  hosts:
    PVE1.lan.luckyh.de:
    PVE2.lan.luckyh.de:
linux:
  hosts:
    DC01-ucs.lan.luckyh.de:
    DC02-ucs.lan.luckyh.de:
    gardenpi.lan.luckyh.de:
    octopi.lan.luckyh.de:
  vars:
    ansible_user: nasadmin
    ansible_password: na5adM!n
    ansible_become: yes
    ansible_become_pass: na5adM!n
