# File: verify_interface_status.yml
---
- name: Cisco show version example
  hosts: cisco
  gather_facts: false

  vars: # for execution environment

    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_become: no
    ansible_become_method: disable

  tasks:

  - name: Gather only the config and default facts
    cisco.ios.ios_facts:
      gather_subset:
      - config
  - name: Configurable backup path
    cisco.ios.ios_config:
      backup: true
      backup_options:
        filename: "{{ inventory_hostname }}.cfg"
        dir_path: /home/ansible/backups

  - name: Show facts
    debug:
      msg: "{{ ansible_facts.net_version }}"
