# File: get_interface_status_and_vlans.yml
---
- name: Cisco IOS Interface-Status und VLANs auslesen
  hosts: cisco
  gather_facts: false

  vars_files:
    - ../vault/cisco.yml

  vars:
    ansible_host_key_checking: false
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_become: no
    ansible_become_method: disable

    ansible_user: "{{ vault_cisco_user }}"
    ansible_password: "{{ vault_cisco_password }}"
    ansible_ssh_pass: "{{ vault_cisco_password }}"

  tasks:
    - name: Physikalischen Interface-Status (Up/Down, Speed, Duplex) sammeln
      cisco.ios.ios_interfaces:
        state: gathered
      register: physical_interfaces

    - name: Layer-2 Informationen (VLANs, Access/Trunk) sammeln
      cisco.ios.ios_l2_interfaces:
        state: gathered
      register: l2_interfaces

    - name: Ergebnisse strukturiert im Terminal anzeigen
      ansible.builtin.debug:
        msg:
          - "--- PHYSIKALISCHER STATUS ---"
          - "{{ physical_interfaces.gathered }}"
          - "--- LAYER-2 & VLAN STATUS ---"
          - "{{ l2_interfaces.gathered }}"
