---
- name: SSH-Schlüssel übertragen
  hosts: all
  gather_facts: false

  vars_prompt:
    - name: selected_key_type
      prompt: "Welcher SSH-Schlüsseltyp soll kopiert werden?\n(Optionen: rsa, ed25519, ecdsa, dsa)"
      default: "ed25519"
      private: false

  tasks:
    - name: Lokalen SSH-Schlüssel validieren und einlesen
      delegate_to: localhost
      run_once: true
      ansible.builtin.set_fact:
        ssh_key_content: "{{ lookup('ansible.builtin.file', '~/.ssh/id_' + selected_key_type + '.pub') }}"

    - name: SSH-Schlüssel auf Remote-Host hinterlegen
      ansible.builtin.authorized_key:
        user: "{{ ansible_user | default('root') }}"
        state: present
        key: "{{ ssh_key_content }}"
      become: true
